package test.model;

import java.math.BigDecimal;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table sxyp_redbag_activity_detail
 *
 * @mbggenerated do_not_delete_during_merge
 */
public class SxypRedbagActivityDetail {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.id
     *
     * @mbggenerated
     */
    private Long id;

    /**
     * Database Column Remarks:
     *   促销活动id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.activity_id
     *
     * @mbggenerated
     */
    private Long activityId;

    /**
     * Database Column Remarks:
     *   主题编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.subject_no
     *
     * @mbggenerated
     */
    private String subjectNo;

    /**
     * Database Column Remarks:
     *   最少支付金额
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.min_amount
     *
     * @mbggenerated
     */
    private BigDecimal minAmount;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.create_time
     *
     * @mbggenerated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sxyp_redbag_activity_detail.update_time
     *
     * @mbggenerated
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.id
     *
     * @return the value of sxyp_redbag_activity_detail.id
     *
     * @mbggenerated
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.id
     *
     * @param id the value for sxyp_redbag_activity_detail.id
     *
     * @mbggenerated
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.activity_id
     *
     * @return the value of sxyp_redbag_activity_detail.activity_id
     *
     * @mbggenerated
     */
    public Long getActivityId() {
        return activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.activity_id
     *
     * @param activityId the value for sxyp_redbag_activity_detail.activity_id
     *
     * @mbggenerated
     */
    public void setActivityId(Long activityId) {
        this.activityId = activityId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.subject_no
     *
     * @return the value of sxyp_redbag_activity_detail.subject_no
     *
     * @mbggenerated
     */
    public String getSubjectNo() {
        return subjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.subject_no
     *
     * @param subjectNo the value for sxyp_redbag_activity_detail.subject_no
     *
     * @mbggenerated
     */
    public void setSubjectNo(String subjectNo) {
        this.subjectNo = subjectNo == null ? null : subjectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.min_amount
     *
     * @return the value of sxyp_redbag_activity_detail.min_amount
     *
     * @mbggenerated
     */
    public BigDecimal getMinAmount() {
        return minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.min_amount
     *
     * @param minAmount the value for sxyp_redbag_activity_detail.min_amount
     *
     * @mbggenerated
     */
    public void setMinAmount(BigDecimal minAmount) {
        this.minAmount = minAmount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.create_time
     *
     * @return the value of sxyp_redbag_activity_detail.create_time
     *
     * @mbggenerated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.create_time
     *
     * @param createTime the value for sxyp_redbag_activity_detail.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sxyp_redbag_activity_detail.update_time
     *
     * @return the value of sxyp_redbag_activity_detail.update_time
     *
     * @mbggenerated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sxyp_redbag_activity_detail.update_time
     *
     * @param updateTime the value for sxyp_redbag_activity_detail.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}