package test.dao;

import java.util.List;
import test.model.SxypRedbagActivityDetail;

public interface SxypRedbagActivityDetailMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxyp_redbag_activity_detail
     *
     * @mbggenerated
     */
    int insert(SxypRedbagActivityDetail record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table sxyp_redbag_activity_detail
     *
     * @mbggenerated
     */
    List<SxypRedbagActivityDetail> selectAll();
}